### ISSUE TITLE
Template does not show up in Visual Studio 2022

### ISSUE THREAD

**Issue by Remonell** [Martinii89/BakkesmodPluginTemplate#4]
Is this functionality limited to Visual Studio 2019?

**Comment by Martinii89** [comment]
it's not. If anything it's limited to Visual studio 22 as I recently updated it to the vs22 toolchain and c++20

**Comment by TimKilcullen** [comment]
@Remonell I ran into this issue as well recently. I resolved by modifying the visual studio 22 installation and including "Desktop development with C++" package. This got me to the point where the template showed up in the search results.

**Comment by Remonell** [comment]
@TimKilcullen Thats what did the trick. Thank you!
